package nl.esciencecenter.esight.textures;

import java.nio.ByteBuffer;

/**
 * Generic wrapper for a {@link Texture} made out of a pre-generated ByteBuffer.
 * 
 * @author Maarten van Meersbergen <m.van.meersbergen@esciencecenter.nl>
 * 
 */
public class ByteBufferTexture extends Texture2D {
    /**
     * Default constructor, wrapper for a pre-generated ByteBuffer.
     * Do not forget to call {@link #init(javax.media.opengl.GL3)} before use.
     * 
     * @param glMultitexUnit
     *            The OpenGL-internal MultitexUnit (GL.GL_TEXTUREX) this texture
     *            uses.
     * @param pixelBuffer
     *            The pre-generated ByteBuffer holding the pixels.
     * @param width
     *            The width of this texture.
     * @param height
     *            The height of this texture.
     */
    public ByteBufferTexture(int glMultitexUnit, ByteBuffer pixelBuffer, int width,
            int height) {
        super(glMultitexUnit);

        this.pixelBuffer = pixelBuffer;
        this.width = width;
        this.height = height;
    }
}
